### ISSUE TITLE
测试好像发现一个小bug

### ISSUE THREAD

**Issue by wuyongguoke** [papapalh/Big_File#3]
测试好像发现一个小bug，如下图
![QQ图片20190312171220](https://user-images.githubusercontent.com/23183145/54188196-2678d580-44ea-11e9-985f-86e12e1eb4d0.png)

**Comment by papapalh** [comment]
刚刚看到，这个问题已经修正
感谢~
commit f70c18b8d176d7fd86babd60e1fc4c764e6b893e (HEAD -> master, origin/master, origin/HEAD)
Author: Hong.li <694728639@qq.com>
Date:   Thu Mar 14 10:19:39 2019 +0800

    新建多余文件Bug修正
