### ISSUE TITLE
小于分片大小的文件会报错

### ISSUE THREAD

**Issue by wuyongguoke** [papapalh/Big_File#4]
上传小于分片大小的文件会报错

**Comment by papapalh** [comment]
这个是插件 Webuploader 的问题，小于最小分片的话会无法切分

**Comment by wuyongguoke** [comment]
小于分片我只做了个粗糙的处理
没有分片不会传chunk
// 移入缓存文件保存
        if (isset($post["chunk"])) {
            move_uploaded_file($file["file"]["tmp_name"], $dir . '/' . $post["chunk"]);
        } else {
            move_uploaded_file($file["file"]["tmp_name"], $dir . '/0');
        }

**Comment by papapalh** [comment]
恩恩，总的来说就是 小于最小分片大小/没有分片但是有文件 直接上传就好了

**Comment by wuyongguoke** [comment]
谢谢你

**Comment by papapalh** [comment]
客气啦
